### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by viniN001** [forcedotcom/salesforcedx-vscode-slds#71] opened 2020-11-30 05:34 UTC
- Issue Type: `Bug`
- Extension Name: `salesforce-vscode-slds`
- Extension Version: `1.4.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.51.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by kirupa** [comment] 2020-11-30 06:05
Hi @viniN001 - can you provide more details? It's not clear what the problem is based on what you've commented 😄

**Comment by ambreeen** [comment] 2021-02-18 20:36
Closing this issue since there has been no followup.

**Closed by ambreeen** 2021-02-18 20:36 UTC
